SET IDENTITY_INSERT dbo.Ciudads ON
INSERT INTO dbo.Ciudads  (Id, Nombre) VALUES
(1, 'Areguá'),
(2, 'Asunción'),
(3, 'Ayolas'),
(4, 'Caacupe'),
(5, 'Caaguazu'),
(6, 'Ciudad del Este'),
(7, 'Concepción'),
(8, 'Coronel Bogado'),
(9, 'Coronel Oviedo'),
(10, 'Encarnación'),
(11, 'General Delgado'),
(12, 'Itauguá'),
(13, 'Jesús de Tavarangüé'),
(14, 'Luque'),
(15, 'Paraguarí'),
(16, 'San Pedro del Ycuamandyjú'),
(17, 'Villarrica'),
(18, 'Villa Hayes'),
(19, 'Ypacaraí'),
(20, 'Pilar'),
(21, 'San Cosme'),
(22, 'San Ignacio Misiones'),
(23, 'San Juan Misiones'),
(24, 'Santa María Misiones'),
(25, 'Santiago'),
(26, 'Trinidad'),
(27, 'Quiindy'),
(28, 'Misiones Jesuíticas'),
(30, 'Villa Florida'),
(31, 'Hohenau'),
(32, 'Obligado'),
(33, 'Choré'),
(34, 'Tomás Romero Pereira'),
(35, 'Bella Vista'),
(36, 'Cambyretá'),
(37, 'José Artigas'),
(38, 'Mayor Otaño'),
(39, 'Pirapó'),
(40, 'San Rafael del Paraná'),
(41, 'Caapucú'),
(42, 'Sapucái'),
(43, 'Hernandarias'),
(44, 'Capiatá'),
(45, 'Mariano Roque Alonso'),
(46, 'Ñemby'),
(47, 'Villa Elisa'),
(48, 'Ypané'),
(49, 'Humaitá'),
(50, 'Filadelfia'),
(51, 'Ñu Guazu'),
(52, 'Capitán Miranda'),
(53, 'María Auxiliadora, Itapúa');
SET IDENTITY_INSERT dbo.Pais OFF